kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: gitops-cli
  #namespace: devsecops-config
  annotations:
    description: base image for gitops pipeline tasks
spec:
  source:
    git:
      ref: develop
      uri: "https://github.com/redhat-partner-ecosystem/devhub-bootstrap"
    contextDir: pipelines/builder
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: gitops-cli:1.0.0
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
--- 
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: gitops-cli
  #namespace: devsecops-config
  annotations:
    description: base image for pipeline tasks
spec:
  lookupPolicy:
    local: false