kind: Namespace
apiVersion: v1
metadata:
  name: devhub
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
    - kubernetes
---
kind: Namespace
apiVersion: v1
metadata:
  name: quay
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
    - kubernetes
