kind: ClusterTask
apiVersion: tekton.dev/v1
metadata:
  name: build-node
spec:
  description: |
    Build a static node app
  params:
    - name: CONTEXT
      type: string
    - name: ASSETS_DIR
      type: string
      default: "."
    - name: ARCHIVE_FILE
      type: string
      default: "assets.tar.gz"
    - name: PRUNE_DEPENDENCIES
      type: string
      default: "true"
  steps:
    - name: build
      image: registry.access.redhat.com/ubi8/nodejs-18
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash

        cd "$(params.CONTEXT)"

        echo "---> Installing all dependencies"
        NODE_ENV=development npm install

        echo "---> Building in production mode"
        npm run build --if-present

        if [[ "$(params.PRUNE_DEPENDENCIES)" == "true" ]]; then
          echo "---> Pruning the development dependencies"
          npm prune
        fi

        if [[ "$(params.ASSETS_DIR)" != "." ]]; then
          echo "---> Compressing assets in '$(params.ASSETS_DIR)' to archive '$(params.ARCHIVE_FILE)'"
          ls -la $(params.ASSETS_DIR)
          tar cvzf "$(params.ARCHIVE_FILE)" "$(params.ASSETS_DIR)"
        fi

      volumeMounts:
        - mountPath: /gen-source
          name: gen-source

  volumes:
    - emptyDir: {}
      name: gen-source

  workspaces:
    - mountPath: /workspace/source
      name: source
