kind: ClusterTask
apiVersion: tekton.dev/v1
metadata:
  name: debug
spec:
  description: |
    Debug
  params:
    - name: IMAGE
      type: string
    - name: CONTEXT
      type: string
    - name: NAMESPACE
      type: string
  steps:
    - name: debug
      image: registry.access.redhat.com/ubi8/nodejs-14
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash

        pwd

        ls -la

        ls -la "$(params.CONTEXT)"
      
      volumeMounts:
        - mountPath: /gen-source
          name: gen-source

  volumes:
    - emptyDir: {}
      name: gen-source

  workspaces:
    - mountPath: /workspace/source
      name: source