kind: ClusterTask
apiVersion: tekton.dev/v1
metadata:
  name: get-github-branch
spec:
  description: >-
    Simple script to extract the git branch from a GitHub webhook payload.
  params:
    - name: GIT_BRANCH_REF
      type: string
      description: "The GitHub ref from the webhook payload (property body.ref)"
  results:
    - description: "The GitHub branch the webhook was call originated from e.g. 'main'"
      name: GIT_BRANCH
  steps:
    - name: tag-image
      image: image-registry.openshift-image-registry.svc:5000/devsecops-config/gitops-cli:1.0.0
      script: |
        #!/usr/bin/env bash

        # extract the branch ref
        IFS="/" read -a branchref <<< "$(params.GIT_BRANCH_REF)"

        BRANCH="${branchref[-1]}"

        printf "%s" "${BRANCH}" > "$(results.GIT_BRANCH.path)"
